http: # TODO replace with standalone fail2ban or crowdsec.
    middlewares:
        fail2ban:
            plugin:
                fail2ban:
                    allowlist:
                        ip: ::1,127.0.0.1
                    rules:
                        enabled: "false"
                        bantime: 1m
                        findtime: 10m
                        maxretry: "5"
                        statuscode: 401,403
